spring:
  profiles:
    active: loadInitialData

  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true

server:
  port: 9090

user-config:
  users:
    - username: "user"
      password: "{bcrypt}$2a$10$XvnX9n9vUZa9a8qLpXldSu/mv7Hyc/zTa2TiwddDYp9i6F2E94a6G" # hasło: "some_user"
      role: "USER"
    - username: "admin"
      password: "{bcrypt}$2a$10$QjjZL.v0/o8f0k3IuO0sUu/v/Zh/Y9jxXnnTmV9y0gnSa2B.AGRnG" # hasło: "some_admin"
      role: "ADMIN"
